---
# tasks file for k8s.aws.ec2
- name: Configuration Kubernetes security group
  ec2_group:
        name: "{{ k8s_sg_name }}"
        description: sg for k8s cluster
        profile: "{{ aws_cli_profile }}"
        region: "{{ region }}"
        rules:
               - proto: all
                 cidr_ip: 0.0.0.0/0
                 rule_desc: ALLOWING ALL TRAFFIC

- name: Launching Master Instance
  ec2_instance:
        name: "Kubernetes Master"
        key_name: "{{ key }}"
        profile: "{{ aws_cli_profile }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ imageId }}"
        security_group: "{{ k8s_sg_name }}"
        region: "{{ region }}"
        tags:
          name: kube-master
          type: master

- name: Launching Worker Instances
  ec2_instance:
        name: "Kubernetes Slave{{ item }}"
        key_name: "{{ key }}"
        profile: "{{ aws_cli_profile }}"
        instance_type: "{{ instanceType }}"
        image_id: "{{ imageId }}"
        security_group: "{{ k8s_sg_name }}"
        region: "{{ region }}"                                                                                                  
        tags:
          name: kube-worker
          type: worker
  with_sequence: start=0 end="{{ no_of_slave }}"
